### GET request to example server (refused after api-gateway set
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "John Doe kafka test",
  "email": "test_kafka@example.com",
  "address": "123 main street",
  "dateOfBirth": "1999-08-23",
  "registeredDate": "2026-04-01"
}

###

POST http://localhost:4004/api/patients
Content-Type: application/json

{
  "name": "John Doe api gateway test1",
  "email": "test_api_gateway1@example.com",
  "address": "123 main street",
  "dateOfBirth": "1999-08-23",
  "registeredDate": "2026-04-01"
}
