### GET request to example server
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "John Doe",
  "email": "test@example.com",
  "address": "123 main street",
  "dateOfBirth": "1999-08-23",
  "registeredDate": "2026-04-01"
}

###